"""
Domain models for requests and responses.

Ocean Professional: Keep models expressive with Field descriptions.
"""
from typing import List, Optional, Literal, Dict, Any
from pydantic import BaseModel, Field


class Message(BaseModel):
    role: Literal["user", "assistant", "system"] = Field(..., description="Message role according to chat format.")
    content: str = Field(..., description="Message text content.")


class ChatRequest(BaseModel):
    session_id: Optional[str] = Field(None, description="Existing session ID. If missing, a new session may be created.")
    messages: List[Message] = Field(..., description="List of chat messages including the last user input.")
    context: Optional[Dict[str, Any]] = Field(default=None, description="Optional context like cart items or user profile.")


class ChatResponse(BaseModel):
    session_id: str = Field(..., description="Session ID used for the interaction.")
    reply: str = Field(..., description="Assistant reply message.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional information like citations or intents.")


class QARequest(BaseModel):
    question: str = Field(..., description="User question about products or policies.")
    product_ids: Optional[List[str]] = Field(None, description="Optional specific product IDs to scope the answer.")


class QAResponse(BaseModel):
    answer: str = Field(..., description="Answer generated by the system.")
    related_products: List[str] = Field(default_factory=list, description="IDs of related products mentioned in the answer.")
    confidence: float = Field(default=0.75, description="Confidence score between 0 and 1.")


class Product(BaseModel):
    id: str = Field(..., description="Product unique ID.")
    title: str = Field(..., description="Product title.")
    description: str = Field(..., description="Product description.")
    price: float = Field(..., description="Product price.")
    currency: str = Field(default="USD", description="Currency code.")
    image_url: Optional[str] = Field(default=None, description="Product image URL.")


class ProductSearchRequest(BaseModel):
    query: str = Field(..., description="Search text from user.")
    limit: int = Field(default=10, ge=1, le=50, description="Max products to return.")
    filters: Optional[dict] = Field(default=None, description="Optional filters like category, price range, tags.")


class ProductSearchResponse(BaseModel):
    items: List[Product] = Field(default_factory=list, description="Matched products.")
    total: int = Field(default=0, description="Total matched count (approximate if provider limits).")


class RecommendRequest(BaseModel):
    user_id: Optional[str] = Field(default=None, description="User ID if logged in, else anonymous.")
    recent_product_ids: Optional[List[str]] = Field(default=None, description="Recent products viewed or added to cart.")
    max_results: int = Field(default=6, ge=1, le=24, description="Maximum number of recommendations to return.")


class RecommendResponse(BaseModel):
    items: List[Product] = Field(default_factory=list, description="Recommended products.")
    rationale: str = Field(default="", description="High-level explanation of why items were recommended.")


class CreateSessionRequest(BaseModel):
    initial_context: Optional[Dict[str, Any]] = Field(default=None, description="Optional initial context for the session.")


class SessionInfo(BaseModel):
    session_id: str = Field(..., description="Unique identifier of the session.")
    created_at: str = Field(..., description="ISO timestamp of creation.")
    context: Dict[str, Any] = Field(default_factory=dict, description="Session context payload.")
